## Part 1



    The newly-improved calibration document consists of lines of text; each line originally contained a specific calibration value that the Elves now need to recover. On each line, the calibration value can be found by combining the first digit and the last digit (in that order) to form a single two-digit number.
    
    For example:
    
    1abc2
    pqr3stu8vwx
    a1b2c3d4e5f
    treb7uchet
    In this example, the calibration values of these four lines are 12, 38, 15, and 77. Adding these together produces 142.
    


In [7]:
from numpy import *

In [8]:
S="""
1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet""".strip()

In [9]:
lines=S.split('\n')

In [10]:
for line in lines:
    pass

In [11]:
line

'treb7uchet'

In [15]:
arr=array([ord(_) for _ in line])
arr

array([116, 114, 101,  98,  55, 117,  99, 104, 101, 116])

In [16]:
arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
arr

array([55])

In [19]:
int(chr(arr[0])+chr(arr[-1]))

77

In [20]:
nums=[]
for line in lines:
    arr=array([ord(_) for _ in line])
    arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
    val=int(chr(arr[0])+chr(arr[-1]))
    nums.append(val)

nums,sum(nums)

([12, 38, 15, 77], 142)

In [21]:
S=open('data/day1.txt').read().strip()
lines=S.split('\n')
len(lines)

1000

In [22]:
nums=[]
for line in lines:
    arr=array([ord(_) for _ in line])
    arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
    val=int(chr(arr[0])+chr(arr[-1]))
    nums.append(val)

sum(nums)

55477

## Part 2

    Your calculation isn't quite right. It looks like some of the digits are actually spelled out with letters: one, two, three, four, five, six, seven, eight, and nine also count as valid "digits".
    
    Equipped with this new information, you now need to find the real first and last digit on each line. For example:
    
    two1nine
    eightwothree
    abcone2threexyz
    xtwone3four
    4nineeightseven2
    zoneight234
    7pqrstsixteen
    In this example, the calibration values are 29, 83, 13, 24, 42, 14, and 76. Adding these together produces 281.

In [32]:
S="""
two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen""".strip()
lines=S.split('\n')
len(lines)

7

In [33]:
lines

['two1nine',
 'eightwothree',
 'abcone2threexyz',
 'xtwone3four',
 '4nineeightseven2',
 'zoneight234',
 '7pqrstsixteen']

In [37]:
nums=[]
for line in lines:
    print(line,"::",end="")

    while True:
        idx=[]
        digit_name=[]   # xtwone3four have to deal with two happening before one
        digits=['zero','one','two','three','four','five','six','seven','eight','nine']
        for i,name in enumerate(digits):
            try:
                idx.append(line.index(name))
                digit_name.append(name)
            except ValueError:
                pass
        if idx:
            i=argmin(idx)
            line=line.replace(digit_name[i],str(digits.index(digit_name[i])))
        else:
            break
                          
    print(line)
        
    
    arr=array([ord(_) for _ in line])
    arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
    val=int(chr(arr[0])+chr(arr[-1]))
    nums.append(val)

nums,sum(nums)

two1nine ::219
eightwothree ::8wo3
abcone2threexyz ::abc123xyz
xtwone3four ::x2ne34
4nineeightseven2 ::49872
zoneight234 ::z1ight234
7pqrstsixteen ::7pqrst6teen


([29, 83, 13, 24, 42, 14, 76], 281)

52

In [42]:
S=open('data/day1.txt').read().strip()
lines=S.split('\n')
len(lines)

1000

In [43]:
nums=[]
for line in lines:
    #print(line,"::",end="")
    while True:
        idx=[]
        digit_name=[]   # xtwone3four have to deal with two happening before one
        digits=['zero','one','two','three','four','five','six','seven','eight','nine']
        for i,name in enumerate(digits):
            try:
                idx.append(line.index(name))
                digit_name.append(name)
            except ValueError:
                pass
        if idx:
            i=argmin(idx)
            line=line.replace(digit_name[i],str(digits.index(digit_name[i])))
        else:
            break
                          
        
    #print(line," ",end="")
    arr=array([ord(_) for _ in line])
    arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
    val=int(chr(arr[0])+chr(arr[-1]))
    #print(val)
    nums.append(val)

sum(nums)

54428

In [47]:
min(nums),max(nums)

(11, 99)

somehow this is wrong?  compare to someone elses solution to see which line I'm failing.  it's zfxbzhczcx9eightwockk

In [81]:
import re

file = open('data/day1.txt', 'r')
lines = [line.rstrip() for line in file]
digits = {'zero':0, 'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8, 'nine':9}
totParte1 = 0 
totParte2 = 0 

def parte1(lines):
	somma = 0
	for line in lines:
		num = [c for c in line if c.isnumeric()]
		somma += int(num[0]+num[-1])
	return somma

def parte2(lines):
    somma = 0
    vals=[]
    r = r'(?=(one|two|three|four|five|six|seven|eight|nine|\d))'
    pattern = re.compile(r)
    for line in lines:
        words = []
        for word in pattern.findall(line):
            if(word in digits):
                words.append(str(digits[word]))
            else: 
                words.append(word)	
                
        vals.append(int(words[0]+words[-1]))
        somma += int(words[0]+words[-1])
    return somma,vals

totParte1 = parte1(lines)
totParte2,vals = parte2(lines)
print(totParte2)

54431


In [82]:
len(vals),len(nums)

(1000, 1000)

In [83]:
idx=where(array(vals)!=array(nums))[0]

In [84]:
idx

array([ 14,  17, 171, 258, 277, 343, 379, 414, 486, 563, 575, 687, 692,
       770, 773, 802, 806, 834, 859, 869, 965])

In [85]:
lines[14]

'zfxbzhczcx9eightwockk'

In [86]:
vals[14]

92

In [87]:
nums[14]

98

In [88]:
nums=[]
for line in lines:
    #print(line,"::",end="")
    while True:
        idx=[]
        digit_name=[]   # xtwone3four have to deal with two happening before one and zfxbzhczcx9eightwockk  yuck!  have to iterate chars
        digits=['zero','one','two','three','four','five','six','seven','eight','nine']
        for i,name in enumerate(digits):
            try:
                idx.append(line.index(name))
                digit_name.append(name)
            except ValueError:
                pass
        if idx:
            i=argmin(idx)
            line=line.replace(digit_name[i],str(digits.index(digit_name[i])))
        else:
            break
                          
        
    #print(line," ",end="")
    arr=array([ord(_) for _ in line])
    arr=arr[ (arr>=ord('0')) & (arr<=ord('9'))]
    val=int(chr(arr[0])+chr(arr[-1]))
    #print(val)
    nums.append(val)

sum(nums)

54428

In [68]:
line

'5bszzkpcdxqkvkf7tgc12'

In [76]:
def find_first(line):

    D={'zero':0,
       'one':1,
       'two':2,
       'three':3,
       'four':4,
       'five':5,
       'six':6,
       'seven':7,
       'eight':8,
       'nine':9}

    for i in range(10):
        D[str(i)]=i
    idx=[]
    all_keys=[]
    for key in D:
        try:
            idx.append(line.index(key))
            all_keys.append(key)
        except ValueError:
            pass
         
    i=argmin(idx)
    digit=str(D[all_keys[i]])

    return digit


def find_last(line):

    D={'zero':0,
       'one':1,
       'two':2,
       'three':3,
       'four':4,
       'five':5,
       'six':6,
       'seven':7,
       'eight':8,
       'nine':9}

    line=line[::-1]  # reverse
    for i in range(10):
        D[str(i)]=i
    idx=[]
    all_keys=[]
    for key in D:
        try:
            idx.append(line.index(key[::-1]))
            all_keys.append(key)
        except ValueError:
            pass
         
    i=argmin(idx)
    digit=str(D[all_keys[i]])

    return digit

In [77]:
line

'3894sevenfourfour'

In [79]:
find_first(line),find_last(line)

('3', '4')

In [80]:
for line in lines[:20]:
    print(line,"::",end="")
    print(find_first(line),find_last(line))

9eightone ::9 1
hczsqfour3nxm5seven4 ::4 4
9twopjqkghmbone ::9 1
rhrfthv886vflthreeztvzs ::8 3
tlbtwo62five ::2 5
ninetwonine234nvtlzxzczx ::9 4
28sevenseven ::2 7
2sevensxszqdhjg2threexzjj3 ::2 3
2fvq ::2 2
781dk97eight26 ::7 6
plfrsjtbl6 ::6 6
sixglj13 ::6 3
b3seven6817gjpcxseven ::3 7
3fivenlqcbszfoursixfive6sixfb ::3 6
zfxbzhczcx9eightwockk ::9 2
threedssqrlk2qnpkzpkdddt ::3 2
three67fourkbrlkf7mtbjprrth2 ::3 2
seven3oneightp ::7 8
31three ::3 3
3894sevenfourfour ::3 4


In [89]:
nums=[]
for line in lines:
    val=int(find_first(line)+find_last(line))
    nums.append(val)

sum(nums)

54431